# Version of the dispatch file format
# See https://git.musta.ch/airbnb/jorb_dispatcher_buildkite to know the latest
# version
version: 3
jobs:
  - name: PY2.7-MySQL
    path: _infra/ci/jobs/py27.yml
    options:
        parallelism: 3

  - name: Upload to artifactory
    path: _infra/ci/jobs/upload_package.yml
    options:
       only_run_if: "env('JORB_GIT_BRANCH') == env('JORB_GIT_DEFAULT_BRANCH') || env('JORB_GIT_BRANCH') == 'rb1.10.0'"
